# Documentation
# * mdbook   https://rust-lang.github.io/mdBook/
# * template https://github.com/kg4zow/mdbook-template/

[book]
authors                 = ["John Simpson"]
language                = "en"
multilingual            = false
src                     = "src"
title                   = "Information about reMarkable Tablets"

[output.html]
additional-css          = [ "section-lines.css" , "version-commit.css" ]
curly-quotes            = false
git-repository-url      = "https://github.com/kg4zow/remarkable.jms1.info"
no-section-label        = true
default-theme           = "rust"
preferred-dark-theme    = "ayu"

[preprocessor.version-commit]
renderers               = [ "html" ]
command                 = "./version-commit"

[output.html.redirect]
"/info/calibre.html"            = "/other/calibre.html"
"/info/goMarkableStream.html"   = "/other/goMarkableStream.html"
"/info/rcu.html"                = "/other/rcu.html"
