# Documentation
# * mdbook   https://rust-lang.github.io/mdBook/
# * template https://github.com/kg4zow/mdbook-template/

[book]
authors             = ["John Simpson"]
language            = "en"
multilingual        = false
src                 = "src"
title               = "Information about reMarkable 2"

[output.html]
additional-css      = [ "section-lines.css" , "version-commit.css" ]
curly-quotes        = false
#git-repository-url  = ""
no-section-label    = true

[preprocessor.version-commit]
renderers           = [ "html" ]
command             = "./version-commit"
